language: go

sudo: false

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -parallel=10 -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
